### ISSUE TITLE
s local invoke 的一个 bug, 当codeuri 指定某个具体的 jar 文件或者 zip 文件的时候， s local invoke 会必现报错

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#669]
s local invoke 的一个 bug, 当codeuri 指定某个具体的 jar 文件或者 zip 文件的时候， s local invoke 会必现报错

```yaml
services:
  helloworld: # 业务名称/模块名称
    component:  fc
    actions: 
      pre-deploy: 
        - run: mvn package
          path: ./ 
    props: #  组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: event-java8
        description: 'hello world by serverless devs'
        runtime: java8
        codeUri: ./target
```

出现如下错误

```bash
[2022-03-11 02:46:42] [DEBUG] [FC-CORE] - docker: [object Object] cleanUselessImage: undefined
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - debugPort: undefined
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - debugIde: undefined
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - debuggerPath: undefined
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - debugArgs: undefined
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - event content:
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - The temp directory mounted to /tmp is /Users/songluo/work/start-fc/event-function/fc-event-java8/src/.s/tmp/local/hello-world-service/event-java8
[2022-03-11 02:46:42] [DEBUG] [FC-LOCAL-INVOKE] - reuse flag is true
✖ Project helloworld failed to execute:

ERROR:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245781:33
    at Generator.next (<anonymous>)
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245748:71
    at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.44345.__awaiter (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245744:12)
    at processZipCodeIfNecessary (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245777:12)
    at LocalInvoke.<anonymous> (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245826:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-local-invoke/dist/index.js:245745:58)

TraceId:     acde480011221646966802534
Environment: @serverless-devs/s: 2.0.100, core: 0.1.29, s-home: /Users/songluo/.s, darwin-x64, node-v12.22.10
Documents:   https://www.serverless-devs.com
Discussions: https://github.com/Serverless-Devs/Serverless-Devs/discussions
Issues:      https://github.com/Serverless-Devs/Serverless-Devs/issues

Please copy traceId: acde480011221646966802534 and join Dingding group: 33947367 for consultation.
You can run 's clean --all' to clean Serverless devs.
```

**Comment by wss-git** [comment]
已修复
