### ISSUE TITLE
venv python  s build  local 模式不符合预期

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#746]
在 venv python 本地环境中

s build  local 模式， 并没有将第三方依赖安装到 code 目录下面， 而是安装到了 system 目录下面， 导致代码包里面没有 3rd lib

venv  在 python 开发者中是常用的东西， 快速隔离出一个干净的 python 环境， 主要工具有 

- virtualenv

- conda

**Comment by rsonghuster** [comment]
```bash
root@iZbp13jtbkfo9pfhol23exZ:~/test# pip install virtualenv
...
root@iZbp13jtbkfo9pfhol23exZ:~/test# virtualenv  venv
...
root@iZbp13jtbkfo9pfhol23exZ:~/test# ls
b.js  node_modules  package-lock.json  venv
root@iZbp13jtbkfo9pfhol23exZ:~/test# source venv/bin/activate
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test# mkdir a
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test# cd a
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a# ls
start-fc-event-python3
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a# cd start-fc-event-python3/
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# ls
code  readme.md  s_en.yaml  s.yaml
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# cat  code/requirements.txt
flask
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# s build
[2022-05-13 10:14:56] [INFO] [FC-BUILD] - Build artifact start...
[2022-05-13 10:14:56] [INFO] [FC-BUILD] - build use model useLocal
builder begin to build, runtime is: python3, sourceDir:  /root/test/a/start-fc-event-python3/code
running task: flow PipTaskFlow
running task: PipInstall
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting flask
  Downloading https://mirrors.aliyun.com/pypi/packages/e8/6d/994208daa354f68fd89a34a8bafbeaab26fda84e7af1e35bdaed02b667e6/Flask-1.1.4-py2.py3-none-any.whl (94 kB)
Collecting itsdangerous<2.0,>=0.24
  Downloading https://mirrors.aliyun.com/pypi/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting click<8.0,>=5.1
  Downloading https://mirrors.aliyun.com/pypi/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Jinja2<3.0,>=2.10.1
  Downloading https://mirrors.aliyun.com/pypi/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting Werkzeug<2.0,>=0.15
  Downloading https://mirrors.aliyun.com/pypi/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting MarkupSafe>=0.23
  Downloading https://mirrors.aliyun.com/pypi/packages/fb/40/f3adb7cf24a8012813c5edb20329eb22d5d8e2a0ecf73d21d6b85865da11/MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Installing collected packages: itsdangerous, click, MarkupSafe, Jinja2, Werkzeug, flask
Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 click-7.1.2 flask-1.1.4 itsdangerous-1.1.0
running task: CopySource
[2022-05-13 10:14:58] [INFO] [FC-BUILD] - Build artifact successfully.

Tips for next step
======================
* Invoke Event Function: s local invoke
* Invoke Http Function: s local start
* Deploy Resources: s deploy
End of method: build

(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# ls .s/build/artifacts/hello-world-service/start-fc-event-python3/
index.py          requirements.txt  .s/
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# ls .s/build/artifacts/hello-world-service/start-fc-event-python3/
index.py          requirements.txt  .s/
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# ls .s/build/artifacts/hello-world-service/start-fc-event-python3/.s/python/
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# ls .s/build/artifacts/hello-world-service/start-fc-event-python3/.s/python/
(venv) root@iZbp13jtbkfo9pfhol23exZ:~/test/a/start-fc-event-python3# python
Python 2.7.13 (default, Feb  6 2022, 20:16:18)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> importflask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'importflask' is not defined
>>> importflask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'importflask' is not defined
>>> import flask
>>> flask
<module 'flask' from '/root/test/venv/lib/python2.7/site-packages/flask/__init__.pyc'>
```

**Comment by rsonghuster** [comment]
原因查明：

主要是虚拟环境中不能识别 PYTHONUSERBASE

**Comment by wss-git** [comment]
https://github.com/aliyun/fc-builders/blob/23c833c9bdb19b64048ec0ae6aa4915745a76504/lib/install/task.js#L68  这个不需要修改了，是 cli 模式的处理逻辑，然后用户可以通过-t 手动指定

pip install -t .s/build/artifacts/${serviceName}/${functionName}/.s/python/lib/python/site-packages/  没有指定 版本

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/173780419-b1c567b3-0dc0-4434-be44-fabe9ee0bbd1.png)

在控制台后端应用中心的应用， actions 中的 s build  可以根据 s.yaml 中的 runtime 自动切换 python 版本， 如果使用 pip 的方式,  比如针对  python3.9 runtime：

```
 export PATH=/usr/local/envs/py39/bin:$PATH && export CONDA_DEFAULT_ENV= py39 && pip install -t . xxx
```
