### ISSUE TITLE
s local start 不支持 nodejs18版本

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#897]

**Comment by heimanba** [comment]
TypeError: Cannot read properties of undefined (reading 'split')

    at Object.iDe (C:\Users\EDY\.s\components\devsapp.cn\devsapp\fc-core\dist\index.js:226:319)

    at Object.<anonymous> (C:\Users\EDY\.s\components\devsapp.cn\devsapp\fc-local-invoke\dist\index.js:244513:29)

    at Generator.next (<anonymous>)

    at fulfilled (C:\Users\EDY\.s\components\devsapp.cn\devsapp\fc-local-invoke\dist\index.js:244095:58

**Comment by wss-git** [comment]
https://github.com/devsapp/fc-core/pull/27
