### ISSUE TITLE
端云联调， java build 更新之后， 会出现异常情况

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#97]
1.    s proxied setup -d 5005  这个 terminal 卡死了

```
[2021-07-14T16:54:33.092] [INFO ] [FC-PROXIED-INVOKE] - Detecting code changes and Restarting funtion container...
(node:89465) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Conflict. The container name "/fc_local_1626252873092_xoj0gyz" is already in use by container "77e635d336aa30a2150cb77723ffb69b74eb62d63a80bca8656701bd71036c2a". You have to remove (or rename) that container to be able to reuse that name. 
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:89465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:89465) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Conflict. The container name "/fc_local_1626252873092_xoj0gyz" is already in use by container "77e635d336aa30a2150cb77723ffb69b74eb62d63a80bca8656701bd71036c2a". You have to remove (or rename) that container to be able to reuse that name. 
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:89465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:89465) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Conflict. The container name "/fc_local_1626252873092_xoj0gyz" is already in use by container "77e635d336aa30a2150cb77723ffb69b74eb62d63a80bca8656701bd71036c2a". You have to remove (or rename) that container to be able to reuse that name. 
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:89465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[2021-07-14T16:54:35.161] [INFO ] [FC-PROXIED-INVOKE] - Skip pulling image aliyunfc/runtime-java8:1.9.18...
[2021-07-14T16:54:35.161] [INFO ] [FC-PROXIED-INVOKE] - Reloading success, stopping old container...
[2021-07-14T16:54:35.670] [INFO ] [FC-PROXIED-INVOKE] - Stopping container: e0b6f4bd171dd3cd9ce65dea1b4028ba756fac0ead8c6871cb31f02a3dc3220f
[2021-07-14T16:54:39.431] [INFO ] [FC-PROXIED-INVOKE] - Stopping old container successfully
[2021-07-14T16:54:39.433] [INFO ] [FC-PROXIED-INVOKE] - Detecting code changes and Restarting funtion container...
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
[2021-07-14T16:54:45.911] [INFO ] [FC-PROXIED-INVOKE] - Stopping old container successfully
[2021-07-14T16:54:45.912] [INFO ] [FC-PROXIED-INVOKE] - Detecting code changes and Restarting funtion container...
(node:89465) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Conflict. The container name "/fc_local_1626252873138_x0vwt4a" is already in use by container "0efd7adda9a87a5e02d566778d5d7cfb74abadc44258693e23bf6e18c03df059". You have to remove (or rename) that container to be able to reuse that name. 
    at /Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/Users/songluo/.s/components/devsapp.cn/devsapp/fc-proxied-invoke@0.0.2/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:89465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

```

2.  s proxied clean 会出现 本次  ca 容器还存在的情况

![image](https://user-images.githubusercontent.com/10919599/125594421-5d5872a3-ad8b-42fb-90d6-5ee6ef9a0c18.png)

**Comment by rsonghuster** [comment]
![image](https://user-images.githubusercontent.com/10919599/126281175-e955dd20-2834-4c2d-94ba-aa91e07fa979.png)

现在可以支持 java 的 s build 热更了， 但是还存在一些问题， RT 上图

**Comment by rsonghuster** [comment]
后续继续观察下， 暂时没有出现了
